COMMENT &
Write an assembly program WITH PROCEDURE/S that reads a 3X3 matrix then prints the sum of each column.

Sample input 1:
1 2 3 4 5 6 7 8 9
Sample output 1:
12 15 18
Sample output 2:
10 11 12 13 14 15 16 17 18 
Sample output 2:
39 42 45
&
;======================================================================================================
INCLUDE Irvine32.inc
.data
Arr1 DWORD 1, 2, 3, 4, 5, 6, 7, 8, 9
Arr2 DWORD 10, 11, 12, 13, 14, 15, 16, 17, 18
.code
	main PROC

		;ESI HOLDS THE OFFSET OT THE FIRST ROW
		MOV ESI, OFFSET ARR1
		;EDI HOLDS THE OFFSET OF THE SECOND ROW
		MOV EDI, OFFSET ARR1
		ADD EDI, TYPE ARR1
		;EDX HOLDS THE OFFSET OF THE THIRD ROW
		MOV EDX, ESI
		ADD EDX, TYPE ARR1 * 2
		MOV ECX, 3
		;EBX HOLDS ARRAY TYPE 
		MOV EBX, TYPE ARR1
		CALL SUMCOLUMNS



		;ESI HOLDS THE OFFSET OT THE FIRST COLUMN
		MOV ESI, OFFSET ARR2
		;EDI HOLDS THE OFFSET OF THE SECOND COLUMN
		MOV EDI, OFFSET ARR2
		ADD EDI, TYPE ARR1
		;EDX HOLDS THE OFFSET OF THE THIRD COLUMN
		MOV EDX, ESI
		ADD EDX, TYPE ARR2 * 2
		MOV ECX, 3
		;EBX HOLDS ARRAY TYPE 
		MOV EBX, TYPE ARR2
		CALL SUMCOLUMNS
		


	    exit
	main ENDP


	SUMCOLUMNS PROC USES ESI EDI EDX ECX 

		;SUM OF THE FIRST COLUMN
		MOV EAX, 0
		PUSH ECX
		L1:
			
			ADD EAX, [ESI]
			ADD ESI, EBX
			ADD ESI, EBX
			ADD ESI, EBX


		LOOP L1
		CALL WRITEDEC
		CALL PRINTSPACE
		POP ECX
		;SUM OF THE SECOND COLUMN
		MOV EAX, 0
		PUSH ECX
		L2:
			
			ADD EAX, [EDI]
			ADD EDI, EBX
			ADD EDI, EBX
			ADD EDI, EBX

		LOOP L2
		
		CALL WRITEDEC
		CALL PRINTSPACE
		POP ECX
		PUSH ECX
		;SUM OF THE FIRST COLUMN
		MOV EAX, 0
		L3:
			
			ADD EAX, [EDX]
			ADD EDX, EBX
			ADD EDX, EBX
			ADD EDX, EBX

		LOOP L3
		POP ECX

		CALL WRITEDEC
		CALL PRINTSPACE
		CALL CRLF
		

		RET
	SUMCOLUMNS ENDP

	PRINTSPACE PROC
		PUSHAD

		MOV AL, ' '
		CALL WRITECHAR

		POPAD
		RET
	PRINTSPACE ENDP

	

END main